spring.application.name=budgeting
spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.response-format.type=text
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=áudio em português, esse áudio contém descrição de gastos financeiros